version: '3'

includes:
  go:
    taskfile: ./cmd/Taskfile.yml
    optional: true

vars:
  DOTFILE_DIR: "{{.USER_WORKING_DIR}}"

tasks:
  default:
    desc: åˆ©ç”¨å¯èƒ½ãªã‚¿ã‚¹ã‚¯ä¸€è¦§ã‚’è¡¨ç¤º
    cmds:
      - task --list

  bootstrap:
    desc: åˆå›žã‚»ãƒƒãƒˆã‚¢ãƒƒãƒ—ï¼ˆHomebrew + go-task + å®Œå…¨ã‚»ãƒƒãƒˆã‚¢ãƒƒãƒ—ï¼‰
    cmds:
      - echo "ðŸš€ åˆå›žã‚»ãƒƒãƒˆã‚¢ãƒƒãƒ—ã‚’é–‹å§‹ã—ã¾ã™..."
      - task: _install-homebrew
      - task: _install-go-task
      - task: setup
      - echo "ðŸŽ‰ ã‚»ãƒƒãƒˆã‚¢ãƒƒãƒ—å®Œäº†ï¼æ–°ã—ã„ã‚¿ãƒ¼ãƒŸãƒŠãƒ«ã‚’é–‹ã„ã¦è¨­å®šã‚’æœ‰åŠ¹åŒ–ã—ã¦ãã ã•ã„"

  setup:
    desc: å®Œå…¨ã‚»ãƒƒãƒˆã‚¢ãƒƒãƒ—ï¼ˆãƒ„ãƒ¼ãƒ« + è¨­å®šï¼‰
    cmds:
      - echo "âš™ï¸ ã‚»ãƒƒãƒˆã‚¢ãƒƒãƒ—ã‚’é–‹å§‹ã—ã¾ã™..."
      - task: _install-tools
      - task: _setup-config
      - task: _setup-shell
      - task: _setup-additional
      - echo "âœ… ã‚»ãƒƒãƒˆã‚¢ãƒƒãƒ—å®Œäº†"

  status:
    desc: ã‚»ãƒƒãƒˆã‚¢ãƒƒãƒ—çŠ¶æ³ã‚’ç¢ºèª
    cmds:
      - echo "=== ã‚»ãƒƒãƒˆã‚¢ãƒƒãƒ—çŠ¶æ³ ==="
      - |
        echo "Homebrew: $(command -v brew >/dev/null && echo 'âœ“' || echo 'âœ—')"
        echo "ä¸»è¦ãƒ„ãƒ¼ãƒ«: $(command -v git >/dev/null && command -v gh >/dev/null && echo 'âœ“' || echo 'âœ—')"
        echo "XDGè¨­å®š: $(test -L "$HOME/.zshenv" && echo 'âœ“' || echo 'âœ—')"
        echo "zshè¨­å®š: $(test -L "$HOME/.config/zsh" && echo 'âœ“' || echo 'âœ—')"
        echo "oh-my-zsh: $(test -d "$HOME/.oh-my-zsh" && echo 'âœ“' || echo 'âœ—')"
      - |
        CLAUDE_CONFIG_DIR="$HOME/src/github.com/usadamasa/claude-config"
        if [ -d "$CLAUDE_CONFIG_DIR" ]; then
          task -d "$CLAUDE_CONFIG_DIR" status
        else
          echo "Claudeè¨­å®š: âš ï¸  æœªã‚¯ãƒ­ãƒ¼ãƒ³ (ghq get github.com/usadamasa/claude-config)"
        fi

  test:
    desc: ãƒ†ã‚¹ãƒˆã‚’å®Ÿè¡Œ
    cmds:
      - echo "ðŸ§ª ãƒ†ã‚¹ãƒˆã‚’å®Ÿè¡Œä¸­..."
      - bats tests/
      - task: go:test
      - echo "âœ… ãƒ†ã‚¹ãƒˆå®Œäº†"

  format:
    desc: .editorconfigã«å¾“ã£ã¦ãƒ•ã‚¡ã‚¤ãƒ«ã‚’ãƒ•ã‚©ãƒ¼ãƒžãƒƒãƒˆãƒ»ä¿®æ­£
    cmds:
      - echo "ðŸ“ .editorconfigã«å¾“ã£ã¦ãƒ•ã‚©ãƒ¼ãƒžãƒƒãƒˆä¸­..."
      - |
        if ! command -v editorconfig-checker &> /dev/null; then
          echo "âš ï¸ editorconfig-checkerãŒè¦‹ã¤ã‹ã‚Šã¾ã›ã‚“ã€‚editorconfig-checkerã‚’ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«ã—ã¦ãã ã•ã„"
          exit 1
        fi
        echo "ðŸ” editorconfig-checkerã§ãƒã‚§ãƒƒã‚¯ä¸­..."
        editorconfig-checker
        echo "âœ… ãƒ•ã‚©ãƒ¼ãƒžãƒƒãƒˆãƒã‚§ãƒƒã‚¯å®Œäº†"

  clean:
    desc: è¨­å®šã‚’ã‚¯ãƒªãƒ¼ãƒ³ã‚¢ãƒƒãƒ—ï¼ˆæ³¨æ„ï¼šè¨­å®šãƒ•ã‚¡ã‚¤ãƒ«ãŒå‰Šé™¤ã•ã‚Œã¾ã™ï¼‰
    prompt: "è¨­å®šãƒ•ã‚¡ã‚¤ãƒ«ã‚’å‰Šé™¤ã—ã¾ã™ã‹ï¼Ÿ"
    cmds:
      - rm -f "$HOME/.zshenv"
      - rm -rf "$HOME/.config/zsh" "$HOME/.config/git" "$HOME/.config/vim" "$HOME/.config/npm"
      - |
        CLAUDE_CONFIG_DIR="$HOME/src/github.com/usadamasa/claude-config"
        if [ -d "$CLAUDE_CONFIG_DIR" ]; then
          task -d "$CLAUDE_CONFIG_DIR" clean
        else
          echo "âš ï¸  claude-config æœªã‚¯ãƒ­ãƒ¼ãƒ³: ghq get github.com/usadamasa/claude-config"
        fi
      - echo "ðŸ—‘ï¸ è¨­å®šã‚’ã‚¯ãƒªãƒ¼ãƒ³ã‚¢ãƒƒãƒ—ã—ã¾ã—ãŸ"

  check-xdg:
    desc: Run xdg-ninja to check XDG compliance
    cmds:
      - xdg-ninja --skip-unsupported

  _install-homebrew:
    internal: true
    cmds:
      - |
        if ! command -v brew &> /dev/null; then
          echo "ðŸ“¦ Homebrewã‚’ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«ä¸­..."
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          if [[ -f "/opt/homebrew/bin/brew" ]]; then
            echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
            eval "$(/opt/homebrew/bin/brew shellenv)"
          fi
        fi
    status:
      - command -v brew

  _install-go-task:
    internal: true
    deps: [_install-homebrew]
    cmds:
      - |
        if ! command -v task &> /dev/null; then
          echo "ðŸ“¦ go-taskã‚’ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«ä¸­..."
          brew install go-task
        fi

  _install-tools:
    internal: true
    deps: [_install-homebrew]
    cmds:
      - echo "ðŸ› ï¸ é–‹ç™ºãƒ„ãƒ¼ãƒ«ã‚’ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«ä¸­..."
      - |
        brew install \
          bats-core \
          direnv \
          editorconfig \
          gh \
          ghq \
          git \
          git-now \
          jq \
          peco \
          pipx \
          tig \
          xdg-ninja \
          zsh \
        2>/dev/null || echo "âš ï¸ ä¸€éƒ¨ãƒ„ãƒ¼ãƒ«ã¯æ—¢ã«ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«æ¸ˆã¿ã§ã™"

  _setup-config:
    internal: true
    cmds:
      - echo "âš™ï¸ è¨­å®šãƒ•ã‚¡ã‚¤ãƒ«ã‚’ã‚»ãƒƒãƒˆã‚¢ãƒƒãƒ—ä¸­..."
      - ln -sfn "{{.DOTFILE_DIR}}/.zshenv" "$HOME/"
      - mkdir -p "$HOME/.config" "$HOME/.local/share" "$HOME/.cache"
      - rm -rf "$HOME/.config/zsh"
      - ln -sfn "{{.DOTFILE_DIR}}/config/zsh" "$HOME/.config/"
      - ln -sfn "{{.DOTFILE_DIR}}/config/git" "$HOME/.config/"
      - ln -sfn "{{.DOTFILE_DIR}}/config/vim" "$HOME/.config/"
      - ln -sfn "{{.DOTFILE_DIR}}/config/npm" "$HOME/.config/"
      - |
        CLAUDE_CONFIG_DIR="$HOME/src/github.com/usadamasa/claude-config"
        if [ -d "$CLAUDE_CONFIG_DIR" ]; then
          task -d "$CLAUDE_CONFIG_DIR" setup
        else
          echo "âš ï¸  claude-config æœªã‚¯ãƒ­ãƒ¼ãƒ³: ghq get github.com/usadamasa/claude-config"
        fi

  _setup-shell:
    internal: true
    deps: [_install-tools, _setup-config]
    cmds:
      - echo "ðŸš ã‚·ã‚§ãƒ«ç’°å¢ƒã‚’ã‚»ãƒƒãƒˆã‚¢ãƒƒãƒ—ä¸­..."
      - |
        if [ ! -d "$HOME/.oh-my-zsh" ]; then
          RUNZSH=no sh -c "$(curl -fsSL https://install.ohmyz.sh/)"
        fi
      - |
        ZSH_CUSTOM="$HOME/.oh-my-zsh/custom"
        if [ ! -d "$ZSH_CUSTOM/plugins/zsh-autosuggestions" ]; then
          git clone https://github.com/zsh-users/zsh-autosuggestions "$ZSH_CUSTOM/plugins/zsh-autosuggestions"
        fi
        if [ ! -d "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting" ]; then
          git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting"
        fi

  _setup-additional:
    internal: true
    deps: [_install-tools]
    cmds:
      - echo "ðŸ› ï¸ è¿½åŠ ãƒ„ãƒ¼ãƒ«ã‚’ã‚»ãƒƒãƒˆã‚¢ãƒƒãƒ—ä¸­..."
      - mkdir -p "$HOME/.local/share/vim" "$HOME/.cache/vim/swap" "$HOME/.cache/vim/backup"
      - |
        if ! command -v powerline-shell &> /dev/null; then
          pipx install powerline-shell
        fi
      - |
        brew install --cask \
          font-cica \
          jetbrains-toolbox \
          visual-studio-code \
        2>/dev/null || true
      - |
        if command -v gh &> /dev/null && ! gh extension list | grep -q "seachicken/gh-poi"; then
          gh extension install seachicken/gh-poi
        fi
