version: '3'

tasks:
  test:
    desc: Go テストを実行
    cmds:
      - go test ./cmd/...

  test-v:
    desc: Go テストを詳細モードで実行
    cmds:
      - go test -v ./cmd/...

  build:
    desc: Go バイナリをビルド
    cmds:
      - go build ./cmd/...

  vet:
    desc: Go vet を実行
    cmds:
      - go vet ./cmd/...
